services:
  - type: web
    name: youtube-mp3-api
    env: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg python3-pip
      pip3 install yt-dlp
      npm install
    startCommand: npm start
